Cập nhật 2 bài tìm hiểu về Iot và Dapper
HPCC-Cloud-Computing/distributed-tracing-general pull request #1
Opened 2017-03-29 16:43 UTC by vtdat

Đây là 2 bài e tìm hiểu về IoT và Dapper.

2017-03-30 15:38 UTC, tovin07 commented
Em tách 2 tài liệu ra thành 2 pull requests nhé. Cho dễ theo dõi :D

2017-03-31 04:52 UTC, duyleomessi commented
Bài của em về Iot và dapper

[Iot.docx](https://github.com/HPCC-Cloud-Computing/distributed-tracing-general/files/884561/Iot.docx)
[Dapper1.docx](https://github.com/HPCC-Cloud-Computing/distributed-tracing-general/files/884562/Dapper1.docx)

2017-03-31 06:33 UTC, tovin07 commented
Anh có mấy comment thế này.
Về nội dung:
Em cùng với @duyleomessi và @vttrinh cùng thảo luận xem cắt ghép với nhau thế nào để cho ra chung 1 sản phẩm. Mỗi bài 1 cmmit nhé.
1. Bài IoT thành 1 commit
2. Bài Dapper thành 1 commit
3. Phần tìm hiểu về Uber Jaeger thì đến đâu rồi cả 3 đứa @duyleomessi @vtdat @vttrinh? Phần này có thể tạo thành 1 pull request khác. Tuy nhiên, cứ có tìm hiểu/cài đặt/thử nghiệm đến đâu thì cũng viết hết ra nhé, mấy anh em review dần dần, có đến đâu review đến đấy.
Anh thấy phần nội dung của @duyleomessi có thể ghép được khá nhiều ý với em.


Về hình thức:
1. Commit message có nghĩa một chút em ơi. Ví dụ em có thể tham khảo ở đây (convention mà Angular - from Google sử dụng): https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines
2. Vì cả 3 đứa cùng gộp chung vào 1 pull request nên tên các file em không cần phải đặt prefix dat_ ở trước nữa.

2017-03-31 06:50 UTC, duyleomessi commented
[Iot.docx](https://github.com/HPCC-Cloud-Computing/distributed-tracing-general/files/884740/Iot.docx)
[Dapper1.docx](https://github.com/HPCC-Cloud-Computing/distributed-tracing-general/files/884741/Dapper1.docx)

2017-03-31 07:13 UTC, duyleomessi commented on distributed-tracing-basic/dat_dapper.md
> +Một yêu cầu nữa cũng đáng chú ý là dữ liệu sau khi được “tracing” phải được sẵn sàng để mang đi sử lý ngay sau khi được tạo ra: lý tưởng nhất là trong vòng 1 phút.
### Cách đạt được key design
 Application-level transparency đạt được bằng cách hạn chế cá công cụ dò tìm cốt lõi của thằng dapper thay vào đó người ta dùng  tập hợp nhỏ các luồng phổ biến, kiểm soát dòng chảy và các thư viện RPC. Trong môi trường của google, tất cả ứng dụng sử dung chung các mô hình luồng, kiểm soát dòng chảy và hệ thống RPC nên việc hận chế các công cụ dò tìm thành các tập hợn các thư việc chung.
 Scalability và low overhead đạt được bằng cách sử dụng các sampling. Người ta nhận thấy rằng một sample của 1 trong 1000 yêu cầu (request) cung cấp đủ thông tin cho việc theo dấu, truy tìm dữ liệu.

2017-03-31 09:32 UTC, tovin07 requested changes
@vtdat anh có mấy comment nhanh như dưới.

2017-03-31 09:32 UTC, tovin07 commented on distributed-tracing-basic/dat_dapper.md
> +Dapper được xây dựng dựa trên 2 mục đích cơ bản: sử dụng phổ biến và quản lý liên tục. Việc được sử dụng phổ biến rất quan trọng bởi vì sự hiệu quả của cơ sở hạ tầng theo dõi sẽ bị ảnh hưởng nếu một
"mục tiêu" chứ không phải "mục đích"

2017-03-31 09:32 UTC, tovin07 commented on distributed-tracing-basic/dat_dapper.md
> +### 1.1. Chi phí thấp (low overheads):
có thể hiểu là đội ngũ triển khai và vận hành

2017-03-31 09:32 UTC, tovin07 commented on distributed-tracing-basic/dat_dapper.md
> +### 1.2. Application-level transparency:
Trong suốt ở mức ứng dụng (hoặc không cần dịch)

2017-03-31 09:32 UTC, tovin07 commented on distributed-tracing-basic/dat_dapper.md
> +Hệ thống quản lý sẽ khó có thể bị nhận ra bởi những người lập trình ứng dụng. Một hệ thống quản lý được xây dựng dựa trên việc kết hợp trực tiếp ở tầng ứng dụng sẽ trở nên cực kỳ mỏng manh. Sử bỏ xót
Đoạn này ý là sao em? Anh tháy word by word quá lại thạnh tối nghĩa. Em có thể trình bày theo cách hiểu của em, nôm na nhất có thể ấy.

2017-03-31 09:32 UTC, tovin07 commented on distributed-tracing-basic/dat_dapper.md
> +Một yêu cầu nữa cũng đáng chú ý là dữ liệu sau khi được “tracing” phải được sẵn sàng để mang đi sử lý ngay sau khi được tạo ra: lý tưởng nhất là trong vòng 1 phút.
tracing có thể được dịch là truy vết, hiện tại cũng không có ai đã dịch nó cả, anh em mình hãy là người đi đầu trong việc dùng từ :))

2017-03-31 09:32 UTC, tovin07 commented on distributed-tracing-basic/dat_dapper.md
> +* Khi một luồng xử lý một “traced control path”, Dapper đặt một ngữ cảnh theo dõi vào lưu trữ nội bộ của luồng. Ngữ cảnh theo dõi là một bộ chứa nhỏ, dễ dàng copy của những tính chất của một nhịp như
Em cứ để là trace context đi

2017-03-31 09:32 UTC, tovin07 commented on distributed-tracing-basic/dat_dapper.md
> +* Khi việc tính toán được làm không đồng bồ, phần lớn lập trình viên của Google sử dụng một thư viện quản lý “flow” để xây dựng callbacks và lên kế hoạch nó trong một “thread pool” và trong những “ex
*đảm bảo

2017-03-31 09:32 UTC, tovin07 commented on distributed-tracing-basic/dat_dapper.md
> +* Hầu hết việc trao đổi thông tin nội bộ trong một process của Google được xây dựng dựa trên một RPC framework và “bindings” trong C++ và Java. Và framework này sẽ định nghĩa “spans” theo những RPCs
Về cách viết thì đúng rồi nhưng không rõ nghĩa. Again, em dịch theo ý hiểu nhé.

2017-03-31 09:32 UTC, tovin07 commented on distributed-tracing-basic/dat_dapper.md
> +## 3.Tổ chức dữ liệu
Đoạn này đang khó dịch à @vtdat ? @vttrinh và @duyleomessi hỗ trợ hoặc bổ sung tư phần tìm hiểu của hai đứa vào đây được không?

2017-03-31 09:32 UTC, tovin07 commented on distributed-tracing-basic/dat_dapper.md
> +## 4. Đánh giá
Đoạn này cũng thế!

2017-03-31 09:32 UTC, tovin07 commented on iot-at-a-glance/dat.md
> +#### 2.1.1. Thu thập và xử lý thông tin
Đừng viết tắt VD nhá

2017-03-31 09:32 UTC, tovin07 commented on iot-at-a-glance/dat.md
> +## 6. References
Cho thêm nguồn tham khảo từ tài liệu em nhận được từ thày Minh nữa nhé

2017-03-31 09:37 UTC, tovin07 commented on distributed-tracing-basic/dat_dapper.md
> +Một yêu cầu nữa cũng đáng chú ý là dữ liệu sau khi được “tracing” phải được sẵn sàng để mang đi sử lý ngay sau khi được tạo ra: lý tưởng nhất là trong vòng 1 phút.
Hai đứa viết về mặt nội dung thì chuẩn rồi, nhưng về mặt diễn giải để cho thoát ý dễ hiểu thì chưa ổn. Thay vì dịch thuần túy, hai đứa thử viêt theo ý hiểu xem sao.

2017-04-01 00:43 UTC, Nobita4116 commented on iot-at-a-glance/dat.md
> +## 5. Lĩnh vực sử dụng IoT
Công nghệ hỗ trợ IOT
[https://pbs.twimg.com/media/C0THVDKVIAAFO35.jpg](url)

2017-04-01 01:02 UTC, Nobita4116 commented on iot-at-a-glance/dat.md
> +![Four iot usage models](iotmodels.png)
Phần này e lại thấy bài viết của Duy đầy đủ hơn

2017-04-01 01:24 UTC, Nobita4116 commented on distributed-tracing-basic/dat_dapper.md
> +We model Dapper traces using trees, spans, and annotations. In a Dapper trace tree, the tree nodes are basic units of work which we refer to as spans. The edges indicate a casual relationship between
Chúng tôi mô hình vết Dapper sử dụng cây, nhịp, và chú thích. Trong một cây dấu vết Dapper, các nút cây là đơn vị cơ bản của công việc mà chúng tôi gọi là nhịp. Các cạnh chỉ ra một mối quan hệ giữa một nhịp và nhịp cha. Độc lập vị trí của nó trong một dấu vết cây lớn hơn, tuy nhiên, một nhịp cũng là thanh thời gian hồ sơ ghi lại ngày tháng mà mã hóa của từng nhịp bắt đầu và ngày kết thúc về mặt thời gian.

2017-04-04 03:20 UTC, closed without merging

2017-04-04 03:20 UTC, tovin07 commented
Close cái này để tiếp tục làm chuẩn chỉnh hơn với cái #4