add document for opentracing
HPCC-Cloud-Computing/distributed-tracing-general pull request #6
Opened 2017-04-15 02:23 UTC by vtdat

1. History
2. Opentracing api
3. Compatible projects
4. Supporting language and client
5. Data model

2017-04-15 02:24 UTC, vtdat commented
@duyleomessi @tovin07 @Nobita4116

2017-04-15 07:53 UTC, Nobita4116 commented on docs/opentracing/opentracing.md
> +## 5. Data model của OpenTracing
![The opentracing software architecture](https://cloud.githubusercontent.com/assets/25746756/25061926/4baa3b7e-21eb-11e7-8032-f0be30dd5d2c.png)

2017-04-15 07:54 UTC, Nobita4116 commented on docs/opentracing/opentracing.md
> +## 5. Data model của OpenTracing
The OpenTracing software architecture

2017-04-15 08:02 UTC, tovin07 commented on docs/opentracing/opentracing.md
> +![relationship](relationship.png)
![otht_1](https://cloud.githubusercontent.com/assets/1128186/25061963/6d9cdef2-21ec-11e7-9866-33834329a248.png)
Anh thấy cái hình này nó cứ méo méo nhỉ :))

2017-04-15 08:03 UTC, tovin07 commented on docs/opentracing/opentracing.md
> +![span](span.png)
![otht_0](https://cloud.githubusercontent.com/assets/1128186/25061968/944f0f66-21ec-11e7-9bbe-2b7ceb094950.png)
Hình này bị sao ấy nhỉ?

2017-04-15 08:03 UTC, tovin07 commented on docs/opentracing/opentracing.md
> +Các nhà phát triển và các tổ chức vẫn đang dần chuyển đổi từ việc sử dụng những hệ thống cũ, lớn sang việc sử dụng mô hình kiến trúc microservice hiện đại. Họ làm như vậy vì nhiều lý do thuyết phục:
*nhóm lập trình

2017-04-15 08:03 UTC, Nobita4116 commented on docs/opentracing/opentracing.md
> +## 5. Data model của OpenTracing
Dấu vết trong OpenTracing được xác định một cách ngầm định bởi Spans của chúng . Cụ thể, dấu vết có thể được xem như là một đồ thị trục thẳng (DAG) của Spans , trong đó các cạnh giữa các Spans được gọi là tài liệu tham khảo .

2017-04-15 08:04 UTC, Nobita4116 commented on docs/opentracing/opentracing.md
> +![relationship](relationship.png)
Causal relationships between Spans in a single Trace


        [Span A]  ←←←(the root span)
            |
     +------+------+
     |             |
 [Span B]      [Span C] ←←←(Span C is a `ChildOf` Span A)
     |             |
 [Span D]      +---+-------+
               |           |
           [Span E]    [Span F] >>> [Span G] >>> [Span H]
                                       ↑
                                       ↑
                                       ↑
                         (Span G `FollowsFrom` Span F)
Temporal relationships between Spans in a single Trace


––|–––––––|–––––––|–––––––|–––––––|–––––––|–––––––|–––––––|–> time

 [Span A···················································]
   [Span B··············································]
      [Span D··········································]
    [Span C········································]
         [Span E·······]        [Span F··] [Span G··] [Span H··]

2017-04-15 08:04 UTC, tovin07 commented on docs/opentracing/opentracing.md
> +Điều đó cho thấy khi một hệ thống có lượng truy cập lớn hoặc chia tách thành nhiều dịch vụ, các nhiệm vụ quan trọng sẽ trở nên khó khăn hơn: tối ưu hóa độ trễ người dung, phân tích và tìm nguyên nhân
*dùng

2017-04-15 08:04 UTC, tovin07 commented on docs/opentracing/opentracing.md
> +Các hệ thống truy vết hiện hành (Zipkin,Dapper, HTrace, X-Trace….) được sinh ra nhằm giải quyết những vấn đề trên bằng cách thêm công cụ truy vết vào tầng ứng dụng bằng việc sử dụng những API không t
hiện tại (Zipkin, Dapper, HTrace, X-Trace…)

2017-04-15 08:07 UTC, tovin07 requested changes
Em thêm phần nhận xet của @Nobita4116 và sửa mấy chỗ anh comment nhé.

2017-04-15 08:11 UTC, tovin07 commented on docs/opentracing/opentracing.md
> +## 5. Data model của OpenTracing
`một đồ thị trục thẳng (DAG)`
Cái này không phải là đồ thị trục thẳng em ạ. Nó là đồ thị có hướng không chu trình (Directed Acyclic Graph)

2017-05-03 01:47 UTC, tovin07 commented on distributed-tracing-basic/opentracing/opentracing.md
> +Các nhóm lập trình và các tổ chức vẫn đang dần chuyển đổi từ việc sử dụng những hệ thống cũ, lớn sang việc sử dụng mô hình kiến trúc microservice hiện đại. Họ làm như vậy vì nhiều lý do thuyết phục:
*nhớm -> nhóm
Em check lại chính tả một số chỗ nữa nhé

2017-05-03 01:48 UTC, tovin07 commented on distributed-tracing-basic/opentracing/opentracing.md
> +## 4. Các client được hỗ trợ cùng với các ngôn ngữ.
Đảo phần này với phần 3, đây là các project nhé, phần 3 là các client

2017-05-03 01:50 UTC, tovin07 commented on distributed-tracing-basic/opentracing/opentracing.md
> +* Mối quan hệ giữa spans và một truy vết
Chỗ này em chỉ rõ hai thứ: có các mối quan hệ nào? ChildOf là gì, FollowsFrom là gì? Một span có thể có nhiều cha hay không?

2017-05-03 01:52 UTC, tovin07 commented on distributed-tracing-basic/opentracing/opentracing.md
> +Dấu vết trong OpenTracing được xác định một cách ngầm định bởi spans của chúng. Cụ thể, dấu vết có thể được xem như là một đồ thị có hướng không chu trình (Directed Acyclic Graph) của spans, trong đó
Chỗ này viết OK rồi, thêm ý nhỏ là trace/span là gì, mối quan hệ giữa trace và span.

2017-05-03 01:52 UTC, tovin07 requested changes
Thề, đây là lần review cuối cho pull request này :v

2017-05-04 03:25 UTC, vtdat commented
Đừng anh ơi :'(

2017-05-10 06:39 UTC, merged